### ISSUE TITLE
Design do Projeto Lab-Home

### ISSUE THREAD

**Issue by josealbertorodriguesjunior** [josealbertorodriguesjunior/Lab-Home#1]
- [x] Fazer o Design do Projeto

**Comment by josealbertorodriguesjunior** [comment]
@jeehmilena favor Fazer o design do projeto!!!

**Comment by jeehmilena** [comment]
##Design do projeto

![projeto-junior](https://cloud.githubusercontent.com/assets/8833388/8626273/4d1bd3be-271a-11e5-9e61-ee9d7d40a806.jpg)

**Comment by jeehmilena** [comment]
**IMAGENS DAS LÂMPADAS**

![images](https://cloud.githubusercontent.com/assets/8833388/8626826/2acc455c-271d-11e5-9fc5-b4c75f46282f.jpg)

![lampada-ligada](https://cloud.githubusercontent.com/assets/8833388/8626831/3723693e-271d-11e5-92d5-ce3832b06447.jpg)

**Comment by jeehmilena** [comment]
**LOGO**

![logo](https://cloud.githubusercontent.com/assets/8833388/8626898/ab58754c-271d-11e5-993a-ebe3f376232b.png)
